#### Aliases
aliases = []

#### Dependencies
dependencies = [
  "_ESAbstract.CreateMethodProperty",
  "Object.create",
  "Object.defineProperty",
  "Blob"
]

#### Specification Link
spec = "https://w3c.github.io/FileAPI/#file-section"

#### Documentation Link
docs = "https://developer.mozilla.org/en-US/docs/Web/API/File"

#### License
license = "MIT"

#### Browser compatibility
[browsers]
android = "<38"
bb = "<8"
chrome = "<38"
edge = "<79"
edge_mob = "a"
firefox = "<28"
firefox_mob = "<79"
ie = "*"
ie_mob = "*"
ios_saf = "<10"
op_mini = "*"
op_mob = "<59"
opera = "<25"
safari = "<10"
samsung_mob = "<4"
