name: Unit Test
on:
  push:
    branches:
      - '*'
      - '**'
      - '!master'
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.2
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run test-library
